#include <stdio.h>
#include <list>
#include <vector>
#include <array>
#include <climits>
#include <iostream>
#include <stack>
#include <queue>
#include <assert.h>
#include <string>
#include <iostream>
