#include <stdio.h>
#include <list>
#include <vector>
#include <array>
#include <climits>
#include <iostream>
#include <set>
#include <stack>
#include <queue>
#include <assert.h>
#include <string>
#include <iostream>
#include <stack>
#include <unordered_map>
#include <unordered_set>
#include <memory>
#include <functional>
